"""empty message

Revision ID: c56f703d8236
Revises: None
Create Date: 2016-11-14 16:41:50.241134

"""

# revision identifiers, used by Alembic.
revision = 'c56f703d8236'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('sifre', sa.String(length=40), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dovizAdi', sa.String(length=30), nullable=True),
    sa.Column('mevcutDeger', sa.String(length=30), nullable=True),
    sa.Column('beklenenDeger', sa.String(length=30), nullable=True),
    sa.Column('oranTuru', sa.String(length=10), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('deviceID', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarm')
    op.drop_table('user')
    ### end Alembic commands ###
